kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  triggers: 
    - type: ImageChange
  source: 
    git:
      uri: "https://github.com/ctron/amq-online-example-iot-weather"
      ref: master
  strategy: 
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
  output: 
    to:
      kind: ImageStreamTag
      name: weather-app:latest
