kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: consumer-iot
  labels:
    app: consumer-iot
spec:
  triggers: 
    - type: ImageChange
  source: 
    git:
      uri: "https://github.com/ctron/amq-online-example-iot-camel-consumer"
      ref: master
  strategy: 
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: fuse7-java-openshift:1.2
  output: 
    to:
      kind: ImageStreamTag
      name: consumer-iot:latest

