kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: consumer
spec:
  to:
    kind: Service
    name: consumer
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
