kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: publisher
  name: centos
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "7"
    from:
      kind: DockerImage
      name: docker.io/centos:7
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
