kind: MessagingUser
apiVersion: user.enmasse.io/v1beta1
metadata:
  name: iot.consumer
spec:
  username: consumer
  authentication:
    type: password
    password: dGVzdDEy # test12
  authorization:
  - addresses:  [ "telemetry/<<iot-tenant>>", "telemetry/<<iot-tenant>>/*", "event/<<iot-tenant>>", "event/<<iot-tenant>>/*" ]
    operations: [ "recv" ]
