kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: publisher
  name: go-toolset
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: centos/go-toolset-7-centos7:latest
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source
